apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podchurns.churndrcontroller.churndr.com
spec:
  group: churndrcontroller.churndr.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
  names:
    kind: Podchurn
    plural: podchurns
  scope: Namespaced
