// +build !ignore_autogenerated

/*
Copyright 2019, Luis E Limon

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSKeys) DeepCopyInto(out *AWSKeys) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSKeys.
func (in *AWSKeys) DeepCopy() *AWSKeys {
	if in == nil {
		return nil
	}
	out := new(AWSKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Activity) DeepCopyInto(out *Activity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Activity.
func (in *Activity) DeepCopy() *Activity {
	if in == nil {
		return nil
	}
	out := new(Activity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileWatcher) DeepCopyInto(out *FileWatcher) {
	*out = *in
	out.AWSKeys = in.AWSKeys
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileWatcher.
func (in *FileWatcher) DeepCopy() *FileWatcher {
	if in == nil {
		return nil
	}
	out := new(FileWatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Podchurn) DeepCopyInto(out *Podchurn) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Podchurn.
func (in *Podchurn) DeepCopy() *Podchurn {
	if in == nil {
		return nil
	}
	out := new(Podchurn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Podchurn) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodchurnList) DeepCopyInto(out *PodchurnList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Podchurn, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodchurnList.
func (in *PodchurnList) DeepCopy() *PodchurnList {
	if in == nil {
		return nil
	}
	out := new(PodchurnList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodchurnList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodchurnSpec) DeepCopyInto(out *PodchurnSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.FileWatcher = in.FileWatcher
	in.Workflow.DeepCopyInto(&out.Workflow)
	out.Activity = in.Activity
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodchurnSpec.
func (in *PodchurnSpec) DeepCopy() *PodchurnSpec {
	if in == nil {
		return nil
	}
	out := new(PodchurnSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodchurnStatus) DeepCopyInto(out *PodchurnStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodchurnStatus.
func (in *PodchurnStatus) DeepCopy() *PodchurnStatus {
	if in == nil {
		return nil
	}
	out := new(PodchurnStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkFlow) DeepCopyInto(out *WorkFlow) {
	*out = *in
	if in.WorkflowParameters != nil {
		in, out := &in.WorkflowParameters, &out.WorkflowParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkFlow.
func (in *WorkFlow) DeepCopy() *WorkFlow {
	if in == nil {
		return nil
	}
	out := new(WorkFlow)
	in.DeepCopyInto(out)
	return out
}
