apiVersion: churndrcontroller.churndr.com/v1alpha1
kind: Podchurn
metadata:
  name: test-churn-01
spec:
  notify:
    notificationFrequency: 120
    noiseReductionLookBackTime: 15
    emailTo: luislimon@gmail.com
  podFilters:
    - name: sandbox
      matchRegEx: "sandbox.*"
    - name: Nginx
      matchRegEx: "nginx.*"
  podLogs:
    saveLogs: true
    tailLines: 300
    maxBytes: 4096
    storeType: s3
    bucket: argoscheduler-sample
    region: us-east-1
    awsKeys:
      secret: example-aws-s3-secret
      accessKeyID: accessKey
      secretKeyID: secretKey
  ignoreFinalTermination: true
